### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by Louis-ThomasSchreiber** [auralius/inverse-dynamics-rne#2]
N = rb.I(:,:,i)*wdot(:,i)+cross(w(:,i),rb.I(:,:,i)*w(:,1));

should be 

N = rb.I(:,:,i)*wdot(:,i)+cross(w(:,i),rb.I(:,:,i)*w(:,i));

w(:,1) -> w(:,i)

?

**Comment by auralius** [comment]
Yes, someone informed me in the pull request. I have accepted his inputs
